## Written 2016 by Scott Hardin for the OpenXPKI project
## Copyright (C) 2016 by The OpenXPKI Project

PACKAGE=myperl-buildtools

# Makefile.inc contains common settings for all packages (checked in)
include ../Makefile.inc

