# .travis.yml
#
# Note: Travis will run through the 'before_install' and 'install' steps
# before executing 'make test'

language: perl

# Note: language-pack-de is needed for the i18n test
before_install:
    - sudo apt-get update -qq
    - sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq libmysqlclient-dev mysql-server devscripts build-essential fakeroot libconfig-std-perl libtemplate-perl

# Try to get debug from inst stuff
install:
    - make fetch-perl
    - echo "travis_fold:start:#{make debian}"
    - make debian
    - echo "travis_fold:end:#{make debian}"
    - echo "travis_fold:start:#{make install}"
    - make debian-install
    - echo "travis_fold:end:#{make install}"
    - echo "travis_fold:start:#{make dbd-mysql}"
    - "(cd ex/libdbd-mysql-myperl && make package)"
    - echo "travis_fold:end:#{make dbd-mysql}"
    - sudo dpkg -i ex/libdbd-mysql-myperl*.deb
