# .travis.yml
#
# Note: Travis will run through the 'before_install' and 'install' steps
# before executing 'make test'

language: perl

# Note: language-pack-de is needed for the i18n test
before_install:
    - sudo apt-get update -qq
    - sudo DEBIAN_FRONTEND=noninteractive apt-get install -qq libmysqlclient-dev mysql-server devscripts build-essential fakeroot libconfig-std-perl libtemplate-perl

# Try to get debug from inst stuff
install:
    - echo "TRAVIS=$TRAVIS"
    - make fetch-perl
    - make debian
    - sudo make debian-install
    - ls -l /opt/myperl/bin
    - dpkg -l | grep myperl
    - "(cd ex/libdbd-mysql-myperl && make package)"
    - sudo dpkg -i ex/libdbd-mysql-myperl*.deb
